### ISSUE TITLE
fdisk: bad usage

### ISSUE THREAD

**Issue by AscendLiu** [ikwzm/FPGA-SoC-Linux#12]
Format SD-Card for DE0-Nano-Soc

Create new partions
执行：`sudo sh scripts/format-disk-de0-nano-soc.sh`出错：

fdisk: bad usage
Try 'fdisk --help' for more information.

**Comment by AscendLiu** [comment]
![image](https://github.com/ikwzm/FPGA-SoC-Linux/assets/73326699/1160908a-4aff-421d-bfc2-253d2427b9ab)

**Comment by ikwzm** [comment]
Thanks for the issue.

I tried it here and it works fine here as follows.


```console
shell# sh format-disk-de0-nano-soc.sh

Welcome to fdisk (util-linux 2.37.2).
Changes will remain in memory only, until you decide to write them.
Be careful before using the write command.


Command (m for help): Created a new DOS disklabel with disk identifier 0x0b4b08\
e9.

Command (m for help): Partition type
   p   primary (0 primary, 0 extended, 4 free)
   e   extended (container for logical partitions)
Select (default p): Partition number (1-4, default 1): First sector (2048-62333951, default 2048): Last sector, +/-sectors or +/-size{K,M,G,T,P} (2048-62333951, default 62333951):
Created a new partition 3 of type 'Linux' and of size 8 MiB.
Partition #3 contains a vfat signature.

Command (m for help):
Selected partition 3
Hex code or alias (type L to list all): Changed type of partition 'Linux' to 'unknown'.

Command (m for help): Partition type
   p   primary (1 primary, 0 extended, 3 free)
   e   extended (container for logical partitions)
Select (default p): Partition number (1,2,4, default 1): First sector (18432-62333951, default 18432): Last sector, +/-sectors or +/-size{K,M,G,T,P} (18432-62333951, default 62333951):
Created a new partition 1 of type 'Linux' and of size 100 MiB.

Command (m for help): Partition number (1,3, default 3): Hex code or alias (type L to list all):
Changed type of partition 'Linux' to 'W95 FAT32'.

Command (m for help): Partition type
   p   primary (2 primary, 0 extended, 2 free)
   e   extended (container for logical partitions)
Select (default p): Partition number (2,4, default 2): First sector (223232-62333951, default 223232): Last sector, +/-sectors or +/-size{K,M,G,T,P} (223232-62333951, default 62333951):
Created a new partition 2 of type 'Linux' and of size 29.6 GiB.

Command (m for help): Disk /dev/sda: 29.72 GiB, 31914983424 bytes, 62333952 sec\
tors
Disk model: SD/MMC
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: dos
Disk identifier: 0x0b4b08e9

Device     Boot  Start      End  Sectors  Size Id Type
/dev/sda1        18432   223231   204800  100M  b W95 FAT32
/dev/sda2       223232 62333951 62110720 29.6G 83 Linux
/dev/sda3         2048    18431    16384    8M a2 unknown
artition table entries are not in disk order.

Command (m for help): The partition table has been altered.
Calling ioctl() to re-read partition table.
Syncing disks.
shell#
```

**Comment by AscendLiu** [comment]
Thank you for your answer.But I still can't solve this problem.

I mentioned 'Delete old partitions' in the previous step, which is different from the tutorial. Can you give me some advice on SD card format and partitioning？

FAT32？or EXT4？ NTFS? and MBR? GUID?

I am very interested in learning how to implement this project. Thank you very much.

**Comment by ikwzm** [comment]
I apologize for not being able to help you with your issue.
I do not understand your problem.
I hope you find a solution soon.

**Comment by ztjshaha** [comment]
Hi Sheng,
I guess you can use the DiskGenius tools format the SD card (FAT32 Or other format, I think FAT32 format here.) at windows side, then you run the script file.thanks~ 
Tong

**Comment by AscendLiu** [comment]
> Hi Sheng, I guess you can use the DiskGenius tools format the SD card (FAT32 Or other format, I think FAT32 format here.) at windows side, then you run the script file.thanks~ Tong

Yes, thank you for your answer. I successfully completed the format partition of the SD card using MBR and FAT32, and then used the second method to manually execute the command "run fdisk step by step". 

However, in the next step "Install Device Drivers and Services", I used "window10+Putty+serial port+115200", and it got stuck when I hit U-boot. It's too difficult for beginners to install the system properly.

![image](https://github.com/ikwzm/FPGA-SoC-Linux/assets/73326699/227ba6bc-00b6-4261-a1f4-71fd1c1223f1)

**Comment by ikwzm** [comment]
Q1 What is the type of partition 1? Is it "W95 FAT32"?

Q2 What is the file system for partition 1? Is it "VFAT"?

Q3 What are the contents of partition 1?　Are the following files present?
 * uEnv.txt
 * devicetree-5.10.165-socfpga.dtb
 * devicetree-5.10.165-socfpga.dts
 * vmlinuz-5.10.165-armv7-fpg

**Comment by AscendLiu** [comment]
Sorry, I can't find the record now, but after following the tutorial, the partition situation is the same as in the tutorial, and after booting up, it's like this. Later, I successfully implemented this method[[Debian: Getting Started with the DE0-Nano-SoC Kit](https://forum.digikey.com/t/debian-getting-started-with-the-de0-nano-soc-kit/12434)](https://forum.digikey.com/t/debian-getting-started-with-the-de0-nano-soc-kit/12434#DE0NanoSoCKit-Bootloader:U-Boot)
