### ISSUE TITLE
PYNQのUSB HOSTが死んでいる

### ISSUE THREAD

**Issue by ryuym** [ikwzm/FPGA-SoC-Linux#3]
Branch
=====
FPGA-SoC-Linux v0.3.2

Current status
=====
いつもたいへん貴重な情報を発信していただき，ありがとうございます．

今Pynqのブートイメージと利用させて頂いているのですが，
PynqのUSB HOST(USB OTG)が機能していません．
qiitaの[Zynq + Yocto で USB デバイスをつくってみた](http://qiita.com/ryos36/items/d892a40a695ef54dc5b1)を参考にして，
usb_ulpi=yにしたzImageに置き換えて試してみたのですが，
解決しませんでした．
お手数とは存じますが，解決策があればご教授頂けると幸いです。

**Comment by ikwzm** [comment]
フィードバックありがとうございます。

ZYBO では USB HOST が機能していたので、てっきり PYNQ でも動くだろうと思っていたのですが、そうでもなかったようです。

現在、調査中ですが、なにぶん USB まわりの知見が乏しく難航しています。なにか判ったら報告します。

**Comment by ryuym** [comment]
ありがとうございます．
こちらでも続けて調べてみます．

**Comment by ikwzm** [comment]
fixed 602feecefcecfcc9426a349801c6fc5ebaa5820c

**Comment by ikwzm** [comment]
PYNQ で USB-HOST が動かなかった件について、原因と対処方法をまとめました。次のところを参照してください。

* [「PYNQ-Z1+Linux で USB-HOST が動かない時の対処方法」@Qiita](https://qiita.com/ikwzm/items/0ef8546a2709428e515b)

ありがとうございました。
